# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('bucketlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Bucketlist')),
            ],
        ),
    ]
