# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180313_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlistitems',
            name='bucketlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Bucketlist'),
        ),
    ]
