version: '3.3'
services:
  db:
    image: postgres
  web:
    build: ./Docker
    command: python ./bucketlistrest/manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/bucketlist
    ports:
      - "8081:8081"
    depends_on:
      - db